  require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|

  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = "C:\\Users\\Administrator\\Desktop\\KEY\\llavedocker.pem"
  
  config.vm.provider :openstack do |os, override|
    os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.domain_name = ENV['OS_DOMAIN_NAME']
    os.username = ENV['OS_USERNAME']
    os.password = ENV['OS_PASSWORD']
    os.keypair_name = ENV['OS_KEY_PAIR_NAME']
    os.region = ENV['OS_REGION_NAME']
    os.image = ENV['OS_IMAGE']	
 end
 
 config.vm.define 'linux-server' do |s|
   s.vm.provision "docker"
   s.vm.provision "docker_compose", compose_version: '1.21.2'
   s.vm.provider :openstack do |os, override|
     os.server_name = 'linux'
     os.flavor = 'f1.desktop.small'
	 os.tenant_name = ENV['OS_TENANT_NAME']
    os.project_name = ENV['OS_PROJECT_NAME']
     override.vm.synced_folder '.', '/vagrant', disabled: true
   end
 end
 
 config.vm.define 'linux-server-tomcat' do |s|
   config.vm.provision "shell", path: "install_tomcat.sh"
   s.vm.provider :openstack do |os, override|
     os.server_name = 'tomcat'
     os.flavor = 'f1.desktop.small'
	 os.tenant_name = ENV['OS_TENANT_NAME_TOMCAT']
    os.project_name = ENV['OS_PROJECT_NAME_TOMCAT']
     override.vm.synced_folder '.', '/vagrant', disabled: true
   end
 end
 
end
