format_version: 3
pipelines:
  ariel-quickstart-ci:
    lock_behavior: lockOnFailure
    group: TEST
    materials:
      repo:
        git: https://github.com/pipo411/AG.git
        branch: gocd_yaml
    stages:
      - Build:
          jobs:
            Building:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "quickstart"
              artifacts:
                - build:
                    source: quickstart/build/libs/*.jar
                    destination: war
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - -p
                      - quickstart
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - jacocoTestReport
                      - -p
                      - quickstart/
              artifacts:
                - build:
                    source: quickstart/build/reports/tests/test/index.html
                    destination: html
                - test:
                    source: quickstart/build/test-results/test/*.xml
                    destination: xml
                - build:
                    source: quickstart/build/jacocoHtml/index.html
                    destination: coverage
         
              tabs:
                unit_test: xml/index.html 
                coverage: testReport/index.html
                htmlReports: html/index.html
                