format_version: 3
pipelines:
  ag-quickstart-ci:
    lock_behavior: lockOnFailure
    group: Application
    materials:
      repo:
        git: https://github.com/pipo411/AG.git
        branch: task13-deploy
    stages:
      - Build:
          jobs:
            Building:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - clean
                      - assemble
                      - -p
                      - quickstart
              artifacts:
                - build:
                    source: quickstart/build/libs/*.jar
                    destination: buildJar   
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - test
                      - jacocoTestReport
                      - -p
                      - quickstart
              artifacts:
                - build:
                    source: quickstart/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: quickstart/build/test-results/test/*.xml
                    destination: xml
              tabs:
                unit_test: xml/index.html
                htmlReports: html/index.html
                
      - CodeQuality:
          jobs:
            CodeQuality:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - sonarqube
                      - -p
                      - quickstart
            
  ag-quickstartWebapp-cli:
    lock_behavior: lockOnFailure
    group: Application
    materials:
      repo: 
       git: https://github.com/pipo411/AG.git
       branch: task13-deploy
    stages: 
      - Build: 
          jobs:
            building: 
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - quickstartWeb
              artifacts:
                - build:
                    source: quickstartWeb/build/libs/*.war
                    destination: BuildWar
      - Test:
          jobs:
            Unit_Test: 
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - test
                      - jacocoTestReport
                      - -p
                      - quickstartWeb
              artifacts:
                - build:
                    source:  quickstartWeb/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: quickstartWeb/build/test-results/test/*xml
                    destination: xml               
                - build:
                    source: quickstartWeb/build/jacocoHtml/**/*
                    destination: jacoco
              tabs:
                unit_test: html/index.html
                jacoco: jacoco/index.html
      - Sonarqube:
          jobs:
            analyzing: 
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - "sonarqube"
      - Deploy:
          jobs:
            analyzing: 
              tasks:
                - fetch:
                   stage: Build
                   job: building
                   source: BuildWar/

                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.135.36
                      - -Puser_server=ubuntu
                      - -Pwar_path=BuildWar
                      - -p
                      - quickstartWeb