format_version: 3
pipelines:
  ariel-quickstart-ci:
    lock_behavior: lockOnFailure
    group: Application
    materials:
      repo:
        git: https://github.com/devops-at06/AG.git
        branch: master
    stages:
      - Commit:
          jobs:
            Building:
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - clean
                      - "assemble"
                      - "-p"
                      - "quickstartWeb"   
                     
              artifacts:
                - build:
                    source: quickstartWeb/build/libs/*.jar
                    destination: buildJar   
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - test
                      - jacocoTestReport
                      - -p
                      - quickstartWeb      
              artifacts:
                - build:
                    source: quickstartWeb/build/reports/tests/test/index.html
                    destination: html
                - test:
                    source: quickstartWeb/build/test-results/test/*.xml
                    destination: xml
                - build:
                    source: quickstartWeb/build/jacocoHtml/index.html
                    destination: coverage
                    
              tabs:
                unit_test: xml/index.html
                coverage: testReport/index.html
                htmlReports: html/index.html          
      - CodeQuality:
          jobs:
            CodeQuality: 
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - sonarqube
                      - -p
                      - quickstartWeb
                                                    

