format_version: 3
pipelines:
  quickstartWebapp-cli:
    lock_behavior: lockOnFailure
    group: App_war
    materials:
      repo: 
       git: https://github.com/devops-at06/AG.git
       branch: master
    stages: 
      - Build: 
          jobs:
            building: 
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - quickstartWeb/"
              artifacts:
                - build:
                    source: quickstartWeb/build/libs/*.war
                    destination: Build
      - Test:
          jobs:
            Unit_Test: 
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - test
                      - jacocoTestReport
                      - -p
                      - quickstartWeb/
              artifacts:
                - build:
                    source:  quickstartWeb/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source:quickstartWeb/build/test-results/test/*xml
                    destination: xml               
                - build:
                    source: quickstartWeb/build/jacocoHtml/**/*
                    destination: jacoco
              tabs:
                unit_test: html/index.html
                jacoco: jacoco/index.html
      - Sonarqube:
          jobs:
            analyzing: 
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - "sonarqube"
      - Deploy:
          jobs:
            analyzing: 
              tasks:
                - exec:
                    command: ./quickstartWeb/gradlew
                    arguments:
                      - -b
                      - deploy
                      - deploy
                      - -Pdev_server=10.28.135.36
                      - -p
                      - quickstartWeb/

                                                    

